spring:
  security:
    jwt:
      secret: Bx3iR7qz9rH5WsYvuJpDjKg9GmPt2fEL
      expiration: 86400000
      token-prefix: Bearer
      token-header: Authorization
      public-urls:
        - /api/users/register
      validate-token-expiration: true
  datasource:
    url: jdbc:postgresql://localhost:5433/database
    username: postgres
    password: lavr3103
    driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      open-in-view: false
server:
  port: 8080
logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.boot: info

